name: OSX
on: [push, pull_request]
jobs:

  test:
    name: Startup test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'galaxy root'
    - name: Cache pip dir
      uses: actions/cache@v1
      id: pip-cache
      with:
        path: ~/Library/Caches/pip
        # scripts/common_startup.sh creates a conda env for Galaxy containing Python 3.6
        key: pip-cache-3.6-${{ hashFiles('galaxy root/requirements.txt') }}
    - name: Install tox
      run: pip install tox
    - name: Install and activate miniconda  # use this job to test using Python from a conda environment
      uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: ''
    - name: run tests
      run: tox -e first_startup
      shell: bash -l {0}  # need this to have CONDA_EXE set
      working-directory: 'galaxy root'
